import { randomUUID } from "node:crypto";

export class EnvelopeFactory {
  constructor({
    source,
    defaultVersion = "1.0.0",
    idGenerator = randomUUID,
    clock = () => new Date().toISOString(),
  } = {}) {
    this._source = source;
    this._defaultVersion = defaultVersion;
    this._idGenerator = idGenerator;
    this._clock = clock;
  }

  createEvent(meta, data) {
    return this.create(
      {
        ...meta,
        kind: "event",
      },
      data,
    );
  }

  createCommand(meta, data) {
    return this.create(
      {
        ...meta,
        kind: "command",
      },
      data,
    );
  }
  create(meta, data = {}) {
    if (!meta || typeof meta !== "object" || Array.isArray(meta)) {
      throw new TypeError("Envelope meta must be a non-null object");
    }

    if (meta.id !== undefined) {
      throw new TypeError("Message id is generated by EnvelopeFactory");
    }

    const { kind, type, streamId, correlationId, causationId, extensions } =
      meta;

    const source = meta.source ?? this._source;
    const version = meta.version ?? this._defaultVersion;

    if (!kind) {
      throw new Error("Envelope kind is required");
    }

    if (!type) {
      throw new Error("Envelope type is required");
    }

    if (!source) {
      throw new Error("Envelope source is required");
    }

    if (!data || typeof data !== "object" || Array.isArray(data)) {
      throw new Error("Envelope data must be an object");
    }

    const id = this._idGenerator();

    return {
      meta: {
        id,
        kind,
        type,
        version,
        source,
        streamId: streamId ?? this._idGenerator(),
        correlationId: correlationId ?? id,
        ...(causationId !== undefined && { causationId }),
        ...(extensions !== undefined && { extensions }),
        timestamp: this._clock(),
      },
      data,
    };
  }
}
